# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/77060/Desktop/COD-exp/monocycle/monocycle.cache/wt [current_project]
set_property parent.project_path C:/Users/77060/Desktop/COD-exp/monocycle/monocycle.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/77060/Desktop/COD-exp/monocycle/monocycle.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/77060/Desktop/COD-exp/monocycle/monocycle.srcs/sources_1/ins.coe
add_files C:/Users/77060/Desktop/COD-exp/monocycle/monocycle.srcs/sources_1/data.coe
read_verilog -library xil_defaultlib {
  C:/Users/77060/Desktop/COD-exp/monocycle/monocycle.srcs/sources_1/new/ADD.v
  C:/Users/77060/Desktop/COD-exp/monocycle/monocycle.srcs/sources_1/new/ALU.v
  C:/Users/77060/Desktop/COD-exp/monocycle/monocycle.srcs/sources_1/new/Control_Unit.v
  C:/Users/77060/Desktop/COD-exp/monocycle/monocycle.srcs/sources_1/new/Debug_Unit.v
  C:/Users/77060/Desktop/COD-exp/monocycle/monocycle.srcs/sources_1/new/MUX2to1.v
  C:/Users/77060/Desktop/COD-exp/monocycle/monocycle.srcs/sources_1/new/MUX_num.v
  C:/Users/77060/Desktop/COD-exp/monocycle/monocycle.srcs/sources_1/new/cpu.v
  C:/Users/77060/Desktop/COD-exp/monocycle/monocycle.srcs/sources_1/new/pc.v
  C:/Users/77060/Desktop/COD-exp/monocycle/monocycle.srcs/sources_1/new/refresh.v
  C:/Users/77060/Desktop/COD-exp/monocycle/monocycle.srcs/sources_1/new/register_file.v
  C:/Users/77060/Desktop/COD-exp/monocycle/monocycle.srcs/sources_1/new/seven_segment.v
  C:/Users/77060/Desktop/COD-exp/monocycle/monocycle.srcs/sources_1/new/signal_edge.v
  C:/Users/77060/Desktop/COD-exp/monocycle/monocycle.srcs/sources_1/new/dbu_top.v
}
read_ip -quiet C:/Users/77060/Desktop/COD-exp/monocycle/monocycle.srcs/sources_1/ip/RAM/RAM.xci
set_property used_in_implementation false [get_files -all c:/Users/77060/Desktop/COD-exp/monocycle/monocycle.srcs/sources_1/ip/RAM/RAM_ooc.xdc]

read_ip -quiet C:/Users/77060/Desktop/COD-exp/monocycle/monocycle.srcs/sources_1/ip/ROM/ROM.xci
set_property used_in_implementation false [get_files -all c:/Users/77060/Desktop/COD-exp/monocycle/monocycle.srcs/sources_1/ip/ROM/ROM_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top dbu_top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef dbu_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file dbu_top_utilization_synth.rpt -pb dbu_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
